export enum PettyCashCategory {
  TRANSPORT = 'TRANSPORT',
  FUEL = 'FUEL',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  COURIER = 'COURIER',
  MAINTENANCE_REPAIRS = 'MAINTENANCE_REPAIRS',
  UTILITIES = 'UTILITIES',
  MEALS_REFRESHMENTS = 'MEALS_REFRESHMENTS',
  PRINTING_STATIONERY = 'PRINTING_STATIONERY',
  GUEST_HOSPITALITY = 'GUEST_HOSPITALITY',
  MISCELLANEOUS = 'MISCELLANEOUS',
  OTHER = 'OTHER',
}

export enum PaymentMethod {
  PETTY_CASH = 'PETTY_CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
}

export enum LedgerEntrySource {
  TASK = 'TASK',
  MANUAL = 'MANUAL',
}

export enum OpeningBalanceSource {
  CARRY_FORWARD = 'CARRY_FORWARD',
  MANUAL = 'MANUAL',
}

export enum AdjustmentType {
  TOP_UP = 'TOP_UP',
  CORRECTION = 'CORRECTION',
}